# Basic air config for PFBackend
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main ./cmd/main.go"
  bin = "tmp/main"
  delay = 1000
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  exclude_file = []
  follow_symlink = true
  send_interrupt = true
  log = "build.log"

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
